---

version: 2.1

executors:
  test:
    parameters:
      version:
        type: string

      line_editor:
        type: string

      compiler:
        type: string

    docker:
      - image: deividrodriguez/byebug:<< parameters.version >>-<< parameters.line_editor >>-<< parameters.compiler >>

jobs:
  spec:
    parameters:
      executor:
        type: executor

    executor: << parameters.executor >>

    steps:
      - checkout

      - restore_cache:
          keys:
            - dependencies-{{ checksum "Gemfile.lock" }}

      - run:
          name: Run CI checks
          command: |
            bin/setup.sh
            bin/rake

      - run:
          name: Save coverage
          command: cc-test-reporter format-coverage --output coverage/codeclimate.$CIRCLE_JOB.json

      - persist_to_workspace:
          root: ./coverage
          paths:
            - codeclimate.*.json

      - save_cache:
          key: dependencies-{{ checksum "Gemfile.lock" }}
          paths:
            - .bundle

  upload_coverage:
    docker:
      - image: deividrodriguez/byebug:2.5.3-readline-clang
        environment:
          - CC_TEST_REPORTER_ID: 02530029b1e956220f05076c590b84b9ab078362c9083312eb2ad41cab138408

    steps:
      - checkout

      - attach_workspace:
          at: ./coverage

      - run:
          name: Upload coverage results to Code Climate
          command: |
            cc-test-reporter sum-coverage coverage/codeclimate.*.json
            cc-test-reporter upload-coverage

workflows:
  version: 2

  test:
    jobs:
      - spec:
          name: prior-to-prior-to-latest-readline-gcc
          executor:
            name: test
            version: 2.3.8
            line_editor: readline
            compiler: gcc

      - spec:
          name: prior-to-prior-to-latest-libedit-gcc
          executor:
            name: test
            version: 2.3.8
            line_editor: libedit
            compiler: gcc

      - spec:
          name: prior-to-prior-to-latest-readline-clang
          executor:
            name: test
            version: 2.3.8
            line_editor: readline
            compiler: clang

      - spec:
          name: prior-to-prior-to-latest-libedit-clang
          executor:
            name: test
            version: 2.3.8
            line_editor: libedit
            compiler: clang

      - spec:
          name: prior-to-latest-readline-gcc
          executor:
            name: test
            version: 2.4.5
            line_editor: readline
            compiler: gcc

      - spec:
          name: prior-to-latest-libedit-gcc
          executor:
            name: test
            version: 2.4.5
            line_editor: libedit
            compiler: gcc

      - spec:
          name: prior-to-latest-readline-clang
          executor:
            name: test
            version: 2.4.5
            line_editor: readline
            compiler: clang

      - spec:
          name: prior-to-latest-libedit-clang
          executor:
            name: test
            version: 2.4.5
            line_editor: libedit
            compiler: clang

      - spec:
          name: latest-readline-gcc
          executor:
            name: test
            version: 2.5.3
            line_editor: readline
            compiler: gcc

      - spec:
          name: latest-libedit-gcc
          executor:
            name: test
            version: 2.5.3
            line_editor: libedit
            compiler: gcc

      - spec:
          name: latest-readline-clang
          executor:
            name: test
            version: 2.5.3
            line_editor: readline
            compiler: clang

      - spec:
          name: latest-libedit-clang
          executor:
            name: test
            version: 2.5.3
            line_editor: libedit
            compiler: clang

      - upload_coverage:
          requires:
            - prior-to-prior-to-latest-readline-gcc
            - prior-to-prior-to-latest-libedit-gcc
            - prior-to-prior-to-latest-readline-clang
            - prior-to-prior-to-latest-libedit-clang

            - prior-to-latest-readline-gcc
            - prior-to-latest-libedit-gcc
            - prior-to-latest-readline-clang
            - prior-to-latest-libedit-clang

            - latest-readline-gcc
            - latest-libedit-gcc
            - latest-readline-clang
            - latest-libedit-clang
