---

version: 2.1

executors:
  test:
    parameters:
      version:
        type: string

      line_editor:
        type: string

      compiler:
        type: string

    docker:
      - image: deividrodriguez/byebug:<< parameters.version >>-<< parameters.line_editor >>-<< parameters.compiler >>

jobs:
  soft_spec:
    parameters:
      executor:
        type: executor

    executor: << parameters.executor >>

    steps:
      - checkout

      - restore_cache:
          keys:
            - dependencies-{{ checksum "Gemfile.lock" }}

      - run:
          name: Run CI checks
          command: (bin/setup.sh && bin/rake test lint) || exit 0

      - run:
          name: Save coverage
          command: cc-test-reporter format-coverage --output coverage/codeclimate.$CIRCLE_JOB.json

      - persist_to_workspace:
          root: ./coverage
          paths:
            - codeclimate.*.json

      - save_cache:
          key: dependencies-{{ checksum "Gemfile.lock" }}
          paths:
            - .bundle


  spec:
    parameters:
      executor:
        type: executor

    executor: << parameters.executor >>

    steps:
      - checkout

      - restore_cache:
          keys:
            - dependencies-{{ checksum "Gemfile.lock" }}

      - run:
          name: Run CI checks
          command: |
            bin/setup.sh
            bin/rake

      - run:
          name: Save coverage
          command: cc-test-reporter format-coverage --output coverage/codeclimate.$CIRCLE_JOB.json

      - persist_to_workspace:
          root: ./coverage
          paths:
            - codeclimate.*.json

      - save_cache:
          key: dependencies-{{ checksum "Gemfile.lock" }}
          paths:
            - .bundle

  upload_coverage:
    docker:
      - image: deividrodriguez/byebug:2.5.3-readline-gcc
        environment:
          - CC_TEST_REPORTER_ID: 02530029b1e956220f05076c590b84b9ab078362c9083312eb2ad41cab138408

    steps:
      - checkout

      - attach_workspace:
          at: ./coverage

      - run:
          name: Upload coverage results to Code Climate
          command: |
            cc-test-reporter sum-coverage coverage/codeclimate.*.json
            cc-test-reporter upload-coverage

  build_and_push_head:
    parameters:
      line_editor:
        type: string

      compiler:
        type: string

    docker:
      - image: deividrodriguez/byebug:2.5.3-readline-gcc

    steps:
      - checkout

      - setup_remote_docker:
          docker_layer_caching: true

      - restore_cache:
          keys:
            - dependencies-{{ checksum "Gemfile.lock" }}

      - run:
          name: Setup environment
          command: bin/setup.sh

      - run:
          name: Build and push docker image
          command: bin/rake docker:build_and_push_head[<< parameters.line_editor >>,<< parameters.compiler >>]

workflows:
  version: 2

  test:
    jobs:
      - spec:
          name: prior-to-prior-to-latest-readline-gcc
          executor:
            name: test
            version: 2.3.8
            line_editor: readline
            compiler: gcc

      - spec:
          name: prior-to-prior-to-latest-libedit-gcc
          executor:
            name: test
            version: 2.3.8
            line_editor: libedit
            compiler: gcc

      - spec:
          name: prior-to-prior-to-latest-readline-clang
          executor:
            name: test
            version: 2.3.8
            line_editor: readline
            compiler: clang

      - spec:
          name: prior-to-prior-to-latest-libedit-clang
          executor:
            name: test
            version: 2.3.8
            line_editor: libedit
            compiler: clang

      - spec:
          name: prior-to-latest-readline-gcc
          executor:
            name: test
            version: 2.4.5
            line_editor: readline
            compiler: gcc

      - spec:
          name: prior-to-latest-libedit-gcc
          executor:
            name: test
            version: 2.4.5
            line_editor: libedit
            compiler: gcc

      - spec:
          name: prior-to-latest-readline-clang
          executor:
            name: test
            version: 2.4.5
            line_editor: readline
            compiler: clang

      - spec:
          name: prior-to-latest-libedit-clang
          executor:
            name: test
            version: 2.4.5
            line_editor: libedit
            compiler: clang

      - spec:
          name: latest-readline-gcc
          executor:
            name: test
            version: 2.5.3
            line_editor: readline
            compiler: gcc

      - spec:
          name: latest-libedit-gcc
          executor:
            name: test
            version: 2.5.3
            line_editor: libedit
            compiler: gcc

      - spec:
          name: latest-readline-clang
          executor:
            name: test
            version: 2.5.3
            line_editor: readline
            compiler: clang

      - spec:
          name: latest-libedit-clang
          executor:
            name: test
            version: 2.5.3
            line_editor: libedit
            compiler: clang

      - soft_spec:
          name: next-readline-gcc
          executor:
            name: test
            version: head
            line_editor: readline
            compiler: gcc

      - soft_spec:
          name: next-libedit-gcc
          executor:
            name: test
            version: head
            line_editor: libedit
            compiler: gcc

      - soft_spec:
          name: next-readline-clang
          executor:
            name: test
            version: head
            line_editor: readline
            compiler: clang

      - soft_spec:
          name: next-libedit-clang
          executor:
            name: test
            version: head
            line_editor: libedit
            compiler: clang

      - upload_coverage:
          requires:
            - prior-to-prior-to-latest-readline-gcc
            - prior-to-prior-to-latest-libedit-gcc
            - prior-to-prior-to-latest-readline-clang
            - prior-to-prior-to-latest-libedit-clang

            - prior-to-latest-readline-gcc
            - prior-to-latest-libedit-gcc
            - prior-to-latest-readline-clang
            - prior-to-latest-libedit-clang

            - latest-readline-gcc
            - latest-libedit-gcc
            - latest-readline-clang
            - latest-libedit-clang

            - next-readline-gcc
            - next-libedit-gcc
            - next-readline-clang
            - next-libedit-clang

  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master

    jobs:
      - build_and_push_head:
          name: build-and-push-head-readline-gcc
          line_editor: readline
          compiler: gcc

      - build_and_push_head:
          name: build-and-push-head-readline-clang
          line_editor: readline
          compiler: clang

      - build_and_push_head:
          name: build-and-push-head-libedit-gcc
          line_editor: libedit
          compiler: gcc

      - build_and_push_head:
          name: build-and-push-head-libedit-clang
          line_editor: libedit
          compiler: clang
